import { Tap } from './tap';

export const TAPS: Tap[] = [
  {id: 1,
  name: "Pliny the Elder",
  brand: "Rogue River",
  price: "$7.00",
  alcoholContent: 7.3,
  pintsRemaining: 124},
  {id: 2,
  name: "Pale Ale",
  brand: "Mirror Pond",
  price: "$5.00",
  alcoholContent: 5.3,
  pintsRemaining: 124},
  {id: 3,
  name: "Hop Venom",
  brand: "Boneyard",
  price: "$6.00",
  alcoholContent: 10.0,
  pintsRemaining: 124},
  {id: 4,
  name: "Lager",
  brand: "Pfreim",
  price: "$6.50",
  alcoholContent: 5.0,
  pintsRemaining: 124},
  {id: 5,
  name: "Double Red",
  brand: "Ninkasi",
  price: "$6.00",
  alcoholContent: 6.2,
  pintsRemaining: 124},
  {id: 6,
  name: "Joe IPA",
  brand: "Ten Barrel",
  price: "$5.50",
  alcoholContent: 6.1,
  pintsRemaining: 124},
  {id: 7,
  name: "Bud Light",
  brand: "Budweiser",
  price: "3.00",
  alcoholContent: 3.2,
  pintsRemaining: 124}
]
